/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTree: typeof import('element-plus/es')['ElTree']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    ILucideAlarmClockMinus: typeof import('~icons/lucide/alarm-clock-minus')['default']
    ILucideArrowLeft2: typeof import('~icons/lucide/arrow-left2')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    ILucideChevronsUpDown: typeof import('~icons/lucide/chevrons-up-down')['default']
    ILucideHome: typeof import('~icons/lucide/home')['default']
    ILucideMoon: typeof import('~icons/lucide/moon')['default']
    ILucidePanelLeft: typeof import('~icons/lucide/panel-left')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeperatorLine: typeof import('./src/components/SeperatorLine.vue')['default']
  }
}
